# Generated by Django 4.0.4 on 2022-06-24 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='information',
            name='markdown',
            field=models.CharField(max_length=4096),
        ),
        migrations.CreateModel(
            name='LikePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likednews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.information')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likednewspair', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
