# Generated by Django 4.0.4 on 2022-06-24 06:33

from django.db import migrations
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_information_description_alter_information_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='x',
            field=news.models.NonStrippingTextField(default=''),
        ),
    ]
