# Generated by Django 4.0.4 on 2022-06-18 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('time_created', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=128)),
                ('game_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionsT1', to='livequiz.game')),
            ],
        ),
    ]
