# Generated by Django 4.0.4 on 2022-06-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0002_questiontype1_number_alter_questiontype1_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype1',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
