# Generated by Django 4.0.4 on 2022-06-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0003_alter_questiontype1_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype1',
            name='game_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='livequiz.game'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='questiontype1',
            order_with_respect_to='game_origin',
        ),
    ]
