# Generated by Django 4.0.4 on 2022-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0004_alter_questiontype1_game_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontype1',
            name='number',
        ),
        migrations.AddField(
            model_name='questiontype1',
            name='answer',
            field=models.CharField(choices=[('1', models.CharField(default='', max_length=64)), ('2', models.CharField(default='', max_length=64)), ('3', models.CharField(blank=True, default='', max_length=64, null=True)), ('4', models.CharField(blank=True, default='', max_length=64, null=True))], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='questiontype1',
            name='choice1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='questiontype1',
            name='choice2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='questiontype1',
            name='choice3',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='questiontype1',
            name='choice4',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
