# Generated by Django 4.0.4 on 2022-06-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livequiz', '0008_remove_gamesession_participants_playersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPairType1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('0', 'unanswered'), ('1', 'c1'), ('2', 'c2'), ('3', 'c3'), ('4', 'c4')], max_length=1)),
                ('gamesession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livequiz.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livequiz.questiontype1')),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerSession',
        ),
    ]
