# Generated by Django 4.0.4 on 2022-06-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0009_answerpairtype1_delete_playersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='stillopen',
            field=models.BooleanField(default=True),
        ),
    ]
