# Generated by Django 4.0.4 on 2022-06-22 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livequiz', '0010_gamesession_stillopen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerpairtype1',
            options={'verbose_name': 'Type 1 Answer Pair'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Game Session'},
        ),
        migrations.AlterModelOptions(
            name='questiontype1',
            options={'verbose_name': 'Type 1 Question'},
        ),
        migrations.RemoveField(
            model_name='answerpairtype1',
            name='gamesession',
        ),
        migrations.RemoveField(
            model_name='answerpairtype1',
            name='player',
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='questiontype1',
            order_with_respect_to=None,
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_joined', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField(default=0)),
                ('gamesession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livequiz.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answerpairtype1',
            name='usersession',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='livequiz.usersession'),
            preserve_default=False,
        ),
    ]
