# Generated by Django 4.0.4 on 2022-06-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0011_alter_answerpairtype1_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
