# Generated by Django 4.0.4 on 2022-06-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0012_rename_time_created_game_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
