# Generated by Django 4.0.4 on 2022-06-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livequiz', '0015_alter_questiontype1_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiontype1',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='questiontype1',
            order_with_respect_to='game_origin',
        ),
    ]
